server: 
  port: 7102

spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    secondary: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mysql?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  redis:
    prefix: xiao-
    host: localhost
    port: 6379
    password: 

third-party: 
  pay:
    ali: 
      APP_ID: 2016092500592160
      account: alsfdv3563@sandbox.com
      notify_url: http://xzl.ngrok.xiaomiqiu.cn/alipay/notify_url
      url: https://openapi.alipaydev.com/gateway.do
      ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvJhuXOx0Wu/1hydV5iKJ2yzZtX03OPCdpI7zEf+8BXOiIhb3jqEd4DlzfRu62YMe0nDxcVPXr80V4dJ9n7iGgz6AM41xXPUYrRpOPqo8OYY7TYl13af0J3BrpsUmg+IekIV9gag9uf4DqqOR4lZ3yRGWLdCnJm+s3l1IT+uvx1585roUf2w9tiSJX+LtYnWyPTPfYHpEKUT3vkdHwG6qwRHSKMGse/I+fspL5j3qZl2GC+o6CTkQWzMzKxDO5o8t2wesjuWIn83wItAMR5PNjVdXDKT8t9am7u/xiaomNQGznKtdHi85pgdW7uZmWFQB1JiI7ft7iLdWyhDZ2+55wwIDAQAB
      APP_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8mG5c7HRa7/WHJ1XmIonbLNm1fTc48J2kjvMR/7wFc6IiFveOoR3gOXN9G7rZgx7ScPFxU9evzRXh0n2fuIaDPoAzjXFc9RitGk4+qjw5hjtNiXXdp/QncGumxSaD4h6QhX2BqD25/gOqo5HiVnfJEZYt0Kcmb6zeXUhP66/HXnzmuhR/bD22JIlf4u1idbI9M99gekQpRPe+R0fAbqrBEdIowax78j5+ykvmPepmXYYL6joJORBbMzMrEM7mjy3bB6yO5YifzfAi0AxHk82NV1cMpPy31qbu7/GJqiY1AbOcq10eLzmmB1bu5mZYVAHUmIjt+3uIt1bKENnb7nnDAgMBAAECggEAVmiUsDiaOwwUd58bKT0L4oLTIOdFBO6hm8LvNYDxWaIYV/wj4pKJSLGp61loK756wbqDtQPQH7kcXIH/ks2Nu9ZIENauaQPXEYCq9uUygLyysRzZBvyrzeIhQKC1u9k/XcH7tgsqdOwgK++TqJsreNF4+HbQDrk+AAfHWO7Ic9RaRiqHNX2Q0vkfLkmQkYWn8LXuXjdHFN9u1ndfw05O50HGMkyiStRp2k2DphcFgON+7y9QofsocXHacVkz7X+JCEkSNbi6kkZm2ehhsNcxq3y4Qp1lqMVYY31YK0svunR8N69MWwUfAiJYqxDH1JGV0QhCFvRUc0OxJvANY7E/oQKBgQDoWTYst5bVHe4mew0ibXYLIqq2maBZSD31ScMrYjx2dIszhuDd3Xf4FW+UN3rAIYsK9OFJ0iD0tRu3/FQh8L9+pMf0CdFb7alm7VKKJk8BMvfFeGRoeroC545+xp7lSHB5VQArmhTgs82WYHM8Ki+te0LiIIMvWxxnZtXz9sUE8QKBgQDPyw4exVz0kqMarZUeTZqaSVWPsoDmBtE3E41KfpfPsykW3E5Sm//KIqo8nA9UC5tC+hAGVAg0O04oPkPoRGn10q1Fc2WpDRYO7mjsGh3fz7EM8Uuz5J+/OiLdRHxsTBQVEGJKR8Vy3K2gSIbvyPbgO5RSmfRMwufF+R4yp2NZ8wKBgB/KbQ4rRHj+cmJTfdWTEo6tfJwlYvo0Vz3jjM+3zjwK8CzprITO06ZfEHhAKwx0yniCTvzxwk6ZJSTEYqKONTVXyIAMg9fHKeGKYTvDyBWK6rnbIinleOQC2M1h0cXfZnxDdBWDLI4eK+gCZGH8B6/96IXWGvz0w2smd+m8fvKRAoGAU1fQTAtBI1+FR/gDbWoW7ncneEFSbfCiDYMsEor//PCRNHgcegnT6JFK0pCNnVoiZhTCRKeDut9mk8GVnx2BmnVrxgVo6wsyo76AGuLGxLQbAWPuxzKV2C9LOJB1j0Jcc65kngJ3cYCNq1IrvRVP39RFw3O4hulN6RvoPszgjn0CgYEAm+Rd/CndyJaXpao545HeQImcED8STCS6GesRXEsWSDvlEIKDIcJTAFCtZWZ3mCM/gPZXUJDSpu9s/2D9iQjCMIICbFjKso/lIAD6S15LElH3TNQojAZU2qNAqFVAbuwLvWQgvRXcS7dwQdLWy6asR72eEe8kFP8fNYHE/bKtXEk=