server: 
  port: 7102

spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    secondary: 
      url: jdbc:mysql://localhost:3306/mysql?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

